import React, { useState } from 'react';
import { User, Mail, Phone, ShieldCheck, Building2, CalendarCheck, ShoppingCart, Heart, Settings, LogOut, LogIn, ChevronRight, Briefcase, Home } from 'lucide-react';
import { useAuth } from '../../context/AuthContext';
import { useProperties } from '../../context/PropertyContext';
import { UserRole } from '../../types';
interface Props { onOpenAuth?: (mode: 'LOGIN' | 'REGISTER') => void; }
export const UserMenuView: React.FC<Props> = ({ onOpenAuth }) => {
  const { currentUser, logout, isAuthenticated, requestProfessionalRole } = useAuth();
  const { setActiveNavTab, showToast } = useProperties();
  const [showProfessional, setShowProfessional] = useState(false);
  const request = async (role: UserRole) => { const r = await requestProfessionalRole(role); if (r.success) { setShowProfessional(false); showToast('Votre demande de compte professionnel a été envoyée pour validation.', 'success'); } else showToast(r.error || 'Demande impossible.', 'error'); };
  if (!isAuthenticated || !currentUser) return <div className="pb-24 max-w-xl mx-auto"><section className="bg-white border border-slate-200 rounded-3xl p-6 text-center shadow-sm"><div className="w-20 h-20 rounded-full bg-[#1e3a8a] text-white flex items-center justify-center mx-auto"><User className="w-9 h-9"/></div><h1 className="text-2xl font-black mt-4">Mon compte</h1><p className="text-sm text-slate-500 mt-2">Connectez-vous ou créez un compte pour accéder aux fonctions personnelles.</p><div className="grid grid-cols-2 gap-3 mt-5"><button onClick={() => onOpenAuth?.('LOGIN')} className="py-3 rounded-xl bg-[#1e3a8a] text-white font-bold text-sm flex items-center justify-center gap-2"><LogIn className="w-4 h-4"/>Se connecter</button><button onClick={() => onOpenAuth?.('REGISTER')} className="py-3 rounded-xl border border-[#1e3a8a] text-[#1e3a8a] font-bold text-sm">Créer un compte</button></div></section></div>;
  const standard = currentUser.role === UserRole.USER;
  const rows = [
    { label:'Mes publications', subtitle:'Biens et annonces que vous avez publiés', icon:Building2, action:()=>setActiveNavTab('owner_properties') },
    { label:'Favoris', subtitle:'Vos annonces enregistrées', icon:Heart, action:()=>showToast('Vos favoris seront chargés depuis votre compte.', 'info') },
    { label:'Mes rendez-vous', subtitle:'Visites et rendez-vous programmés', icon:CalendarCheck, action:()=>showToast('Vos rendez-vous seront chargés depuis votre compte.', 'info') },
    { label:'Mon panier', subtitle:'Articles et biens ajoutés pour achat', icon:ShoppingCart, action:()=>showToast('Votre panier sera chargé depuis votre compte.', 'info') },
    { label:'Paramètres', subtitle:'Sécurité, confidentialité et préférences', icon:Settings, action:()=>showToast('Paramètres du compte.', 'info') },
  ];
  return <div className="pb-24 max-w-xl mx-auto space-y-4"><section className="bg-white border border-slate-200 rounded-3xl overflow-hidden shadow-sm"><div className="h-28 bg-gradient-to-r from-[#1e3a8a] via-blue-700 to-[#16a34a]"/><div className="px-5 pb-5 -mt-10"><div className="w-20 h-20 rounded-full bg-white p-1 shadow-lg"><div className="w-full h-full rounded-full bg-[#1e3a8a] text-white flex items-center justify-center text-2xl font-black overflow-hidden">{currentUser.avatarUrl ? <img src={currentUser.avatarUrl} alt={currentUser.fullName} className="w-full h-full object-cover"/> : currentUser.fullName?.charAt(0)?.toUpperCase()}</div></div><div className="mt-3 flex items-center gap-2"><h1 className="text-xl font-black">{currentUser.fullName}</h1><ShieldCheck className="w-5 h-5 text-emerald-600"/></div><p className="text-xs text-slate-500 mt-1">{standard ? 'Utilisateur standard' : currentUser.role}</p><div className="mt-4 space-y-2 text-sm text-slate-600"><div className="flex gap-2"><Mail className="w-4 h-4"/>{currentUser.email}</div>{currentUser.phone && <div className="flex gap-2"><Phone className="w-4 h-4"/>{currentUser.phone}</div>}</div></div></section>
  {standard && <section className="bg-white border border-blue-200 rounded-3xl p-5 shadow-sm"><div className="flex items-start gap-3"><div className="w-11 h-11 rounded-xl bg-blue-50 text-[#1e3a8a] flex items-center justify-center"><Briefcase className="w-5 h-5"/></div><div className="flex-1"><h2 className="font-black text-slate-900">Créer un compte Business ou Professionnel</h2><p className="text-xs text-slate-500 mt-1">Passez d’un compte standard à un profil professionnel après validation.</p></div></div><button onClick={()=>setShowProfessional(!showProfessional)} className="mt-4 w-full py-3 rounded-xl bg-[#1e3a8a] text-white text-sm font-bold">Choisir mon profil professionnel</button>{showProfessional && <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 mt-3"><button onClick={()=>request(UserRole.AGENT)} className="p-4 rounded-2xl border border-slate-200 text-left hover:border-[#1e3a8a]"><Briefcase className="w-5 h-5 text-[#1e3a8a] mb-2"/><div className="font-black text-sm">Agent / Agence</div><div className="text-[11px] text-slate-500 mt-1">Pour les professionnels et agences immobilières.</div></button><button onClick={()=>request(UserRole.OWNER)} className="p-4 rounded-2xl border border-slate-200 text-left hover:border-[#16a34a]"><Home className="w-5 h-5 text-[#16a34a] mb-2"/><div className="font-black text-sm">Bailleur / Propriétaire</div><div className="text-[11px] text-slate-500 mt-1">Pour gérer et publier vos propres biens.</div></button></div>}</section>}
  <section className="bg-white border border-slate-200 rounded-3xl overflow-hidden shadow-sm divide-y divide-slate-100">{rows.map(r=>{const Icon=r.icon;return <button key={r.label} onClick={r.action} className="w-full p-4 flex items-center gap-3 text-left hover:bg-slate-50"><div className="w-10 h-10 rounded-xl bg-blue-50 text-[#1e3a8a] flex items-center justify-center"><Icon className="w-5 h-5"/></div><div className="flex-1"><div className="font-bold text-sm">{r.label}</div><div className="text-[11px] text-slate-500">{r.subtitle}</div></div><ChevronRight className="w-4 h-4 text-slate-300"/></button>})}</section><button onClick={logout} className="w-full py-3.5 rounded-2xl bg-rose-50 text-rose-700 border border-rose-100 font-bold text-sm flex items-center justify-center gap-2"><LogOut className="w-4 h-4"/>Se déconnecter</button></div>;
};
